### ISSUE TITLE
Presence doesn't update (macOS 11.2.1, Xcode 12.4, Discord 0.0.261)

### ISSUE THREAD

**Issue by keef-khan** [PKBeam/RPFX#1]
RPFX will set the initial project and file I'm working on as my Discord status, but switching to another file or project does not change the status, it continues to show the project and file that was open when RPFX was opened. Restarting Xcode and Discord doesn't seem to adjust the status, only quitting RPFX via Activity Monitor and restarting will adjust the status.

**Comment by PKBeam** [comment]
This was quite an odd bug.

The Timer object that I created to update the presence stopped firing after I updated my macOS from 11.2 to 11.2.1.
I have no idea why this happened, but the issue seems to be fixed after manually adding the Timer to the main RunLoop.

Please try the v1.1.0 release, and let me know if you still have this problem.
