### ISSUE TITLE
Doesn't Prompt for Automation Access

### ISSUE THREAD

**Issue by ghost** [PKBeam/RPFX#4]
Running the app just prints `[RPFX] RPFX launched` and seems to do nothing, no prompts for automation access and nothing happens. It doesn't connect to Discord, just stays there and does nothing. I'm not sure what to do next.

**Comment by PKBeam** [comment]
Is Xcode open? By design, RPFX won't touch your Discord status if Xcode isn't running.

Can you see if RPFX has permission under System Preferences > Security & Privacy > Automation?
If not, try running `tccutil reset AppleEvents com.PKBeam.RPFX` in the terminal and restarting RPFX.
(Although even without permissions, something should still be showing up on your Discord RP.)

If you're still having issues, please let me know what versions of Xcode and macOS you're using.

**Comment by ghost** [comment]
Ohhh it was because I was using Canary, launching Release Discord showed the prompt. Sorry about that!
